-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 00:11:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DocumentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DocumentType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DocumentType` (
  `idDocumentType` INT NOT NULL,
  `name` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDocumentType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `idDocumentType` INT NOT NULL,
  `documentNumber` NCHAR(11) NOT NULL,
  `tradeName` NVARCHAR(100) NOT NULL,
  `legalName` NVARCHAR(100) NOT NULL,
  `registerDate` DATETIME NOT NULL,
  `state` NCHAR(2) NOT NULL,
  PRIMARY KEY (`idCompany`),
  CONSTRAINT `fk_Company_DocumentType`
    FOREIGN KEY (`idDocumentType`)
    REFERENCES `mydb`.`DocumentType` (`idDocumentType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ruc_UNIQUE` ON `mydb`.`Company` (`documentNumber` ASC);

CREATE INDEX `fk_Company_DocumentType_idx` ON `mydb`.`Company` (`idDocumentType` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Phone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Phone` (
  `idPhone` INT NOT NULL AUTO_INCREMENT,
  `number` NVARCHAR(15) NOT NULL,
  `phoneType` NVARCHAR(10) NOT NULL,
  `idCompany` INT NOT NULL,
  PRIMARY KEY (`idPhone`),
  CONSTRAINT `fk_Phone_Company`
    FOREIGN KEY (`idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Phone_Company_idx` ON `mydb`.`Phone` (`idCompany` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL,
  `ubigeo` NVARCHAR(6) NOT NULL,
  `address` NVARCHAR(100) NOT NULL,
  `latitude` DECIMAL(18,10) NULL,
  `longitude` DECIMAL(18,10) NULL,
  `idCompany` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  CONSTRAINT `fk_Address_Company`
    FOREIGN KEY (`idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Address_Company1_idx` ON `mydb`.`Address` (`idCompany` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `firstNames` NVARCHAR(100) NOT NULL,
  `fatherLastname` NVARCHAR(100) NOT NULL,
  `motherLastname` NVARCHAR(100) NOT NULL,
  `idDocumentType` INT NOT NULL,
  `documentNumber` NVARCHAR(15) NOT NULL,
  `email` NVARCHAR(400) NULL,
  PRIMARY KEY (`idPerson`),
  CONSTRAINT `fk_Person_DocumentType`
    FOREIGN KEY (`idDocumentType`)
    REFERENCES `mydb`.`DocumentType` (`idDocumentType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `documentNumber_UNIQUE` ON `mydb`.`Person` (`documentNumber` ASC);

CREATE INDEX `fk_Employee_DocumentType_idx` ON `mydb`.`Person` (`idDocumentType` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmployeeType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeType` (
  `idEmployeeType` INT NOT NULL,
  `name` NVARCHAR(100) NULL,
  PRIMARY KEY (`idEmployeeType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonXCompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PersonXCompany` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PersonXCompany` (
  `idCompany` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `registerDate` DATETIME NOT NULL,
  `startDate` DATETIME NOT NULL,
  `finishDate` DATETIME NULL,
  `salary` DECIMAL(18,2) NOT NULL,
  `idEmployeeType` INT NOT NULL,
  PRIMARY KEY (`idCompany`, `idPerson`),
  CONSTRAINT `fk_PersonXCompany_EmployeeType`
    FOREIGN KEY (`idEmployeeType`)
    REFERENCES `mydb`.`EmployeeType` (`idEmployeeType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PersonXCompany_Company`
    FOREIGN KEY (`idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PersonXCompany_Person`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PersonXCompany_EmployeeType_idx` ON `mydb`.`PersonXCompany` (`idEmployeeType` ASC);

CREATE INDEX `fk_PersonXCompany_Person_idx` ON `mydb`.`PersonXCompany` (`idPerson` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`DocumentType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (0, 'Otros');
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (1, 'L.E / DNI');
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (4, 'Carnet ext.');
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (6, 'RUC');
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (7, 'Pasaporte');
INSERT INTO `mydb`.`DocumentType` (`idDocumentType`, `name`) VALUES (11, 'P. Nac.');

COMMIT;

